Adding navigation to post from notification
noom/Noom-Amity-Social-UIKit pull request #10
Opened 2023-04-04 16:18 UTC by aabolade

* Added `openNotification` closure to `NotificationFeature`

2023-04-04 17:25 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/NotificationFeature.swift
> +        self.openNotification = openNotification
The `String`s here are `postId`s, right? It'd be good to make those strongly-typed, even if it's just wrapping it in a `struct`. Double-check in case this already exists.

2023-04-04 17:25 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/UIViewController+Tooltip.swift
> +                                self?.navigationController?.pushViewController(viewController, animated: true)                            }
Runaway trailing brace

2023-04-04 17:25 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/NotificationFeature.swift
> +            }
This parsing out logic looks brittle and the reducer isn't the best place to put it. Also, looks like `path` is also a `String` (as opposed to url) - `CommunityNotification` might benefit from some strong typing as well.

Is the `postId` the same as `id` in `CommunityNotification`? If so, I don't think you'd even need this logic. If not, it'd move this into `CommunityNotification` under a computed `var`, eg:
```
struct CommunityNotification {
  ...
  // Might be more appropriate to put this outside `CommunityNotification`, not sure 
  enum PostId: Hashable {
    let value: String
  }

  var postId: PostId {
    // Parsing logic
    return .init(value: postId)
  }
```

and change `markNotificationAsRead` and `openNotification` to take `PostId`.

2023-04-04 17:25 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/UIViewController+Tooltip.swift
> +                                self?.presentedViewController?.dismiss(animated: true, completion: onDidClose)
This is duplicating `closeAction`.. Two likely approaches here:
1. Call `closeAction` from the reducer separately before calling `openNotification`
2. Factor out `closeAction` as a closure and reuse it, so as not to duplicate that logic:
```
let closeAction = { [weak self] in
  self?.presentedViewController?.dismiss(animated: true, completion: onDidClose)
}
presentPopover(
  ...
      client: internalNotificationClient,
      closeAction: closeAction,
      openNotification: { [weak self] postId in
        closeAction()
        ...
```

2023-04-04 18:09 UTC, aabolade commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/NotificationFeature.swift
> +            }
No `postId` is not the same as the `id` of the notification

2023-04-05 23:43 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/NotificationFeature.swift
>      private let markNotificationAsRead: (String) -> EffectTask<Action>
The `String` in `markNotificationAsRead` is also ` PostId`, right?

2023-04-05 23:43 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/NotificationFeature.swift
> +        self.openNotification = openNotification
Do you, or are you planning to, ever use these separately? If not, you should just combine it into one callback effect, `openNotification`, and let it handle marking it as read.

2023-04-05 23:43 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/NotificationFeature.swift
>              return markNotificationAsRead(state.id)
`openNotification` is also a "side effect" so it'd be good to model it as `Effect` as well. Doing this as you have right now could create potential races down the road.

If you can't just combine the two into one side-effect like I suggested above, the correct TCA approach would be to be to make `openNotification` an `EffectTask<Action>` as well and then combining them in one of two ways:

* `EffectTask.merge(...)` - runs the effects **at the same time**
* `EffectTask.concatenate(...)` - runs the effects **one after the other**

2023-04-05 23:43 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/NotificationFeature.swift
>      private let markNotificationAsRead: (String) -> EffectTask<Action>
The other thing that is weird about this is that the `Action` that this gives comes way from the outside this TCA scope. There are uses for this but that's probably not what you want here - you generally want the TCA reducer to control the actions it performs based on output of these dependency effects. What I think you wanna do here (and up in the `client` that injects this) is `EffectTask<Void>` that you can `.fireAndForget()`, which will invoke it and map it to a `.none` action. This way, the `NotificationFeature.Action` type doesn't "leak out". Search the codebase for "EffectTask<Void>" for examples.

2023-04-05 23:43 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/UIViewController+Tooltip.swift
> +                                self?.navigationController?.pushViewController(viewController, animated: true)
I didn't catch this before, but this should probably be done by the `dismiss(...)`'s `completion` block, otherwise you're basically dismissing and presenting at the same time, which could cause problems. Probably easier to go back to just duplicating the `dismiss` call like you had before, but tie this VC's presentation to its `completion`:
```
openNotification: { [weak self] postId in
  self?.presentedViewController?.dismiss(animated: true) {
    closeAction()
    let viewController = AmityPostDetailViewController.make(withPostId: postId.value)
    self?.navigationController?.pushViewController(viewController, animated: true)
  }
}
```

Even so, I'm a little nervous that `closeAction` could in theory do it's own UI stuff, which would race `pushViewController`.. Not much we can do about that here, but good to be aware.

2023-04-06 15:18 UTC, superx3man commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/CommunityNotification.swift
> +        return .init(value: value)
I suggest using regular expression to capture the post ID directly, sth like `/post/([0-9]+)`

2023-04-06 15:18 UTC, superx3man commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/NotificationTrayClient.swift
> +    public typealias ViewStore = ViewStoreOf<InternalNotificationTray>
Do you need a view store? And with the introduction of `StoreOf<...>` I found it a bit redundant to create a typealias for `Store` as well.

2023-04-06 15:18 UTC, superx3man commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/NotificationTrayClient.swift
> +            .forEach(\.notifications, action: /Action.notification) { NotificationFeature(markNotificationAsRead: client.markNotificationAsRead, openNotification: openNotification) }
nit: Line break. I think we are doing 120 characters max per line.

2023-04-07 14:09 UTC, aabolade commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/CommunityNotification.swift
> +        return .init(value: value)
@superx3man Sure! FYI because we're below iOS 16 we can't use the new `Regex` API from Swift 5.7 so the code for this will still look unpretty :/

2023-04-07 18:34 UTC, superx3man requested changes
A few things that need to be addessed or answer,
1. The regular expression check should use capture groups.
2. Felt like the `markNotificationAsRead` and `openNotification` effect could be merged into 1.

What about the first PR on this project, are you going to address some feedback there?

2023-04-07 18:34 UTC, superx3man commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/CommunityNotification.swift
> +        let regex = try? NSRegularExpression(pattern: "/post/[a-z0-9]+")
Use capture group instead of `.dropFirst(6)`, specifically "/post/([a-z0-9]+)"

2023-04-07 18:34 UTC, superx3man commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/CommunityNotification.swift
> +        guard let results = regex?.matches(in: path,
nit: newline before `in:`

2023-04-07 18:34 UTC, superx3man commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/CommunityNotification.swift
> +            String(path[Range($0.range, in: path)!])
Always avoid force unwrap.

2023-04-07 18:34 UTC, superx3man commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/InternalNotificationTray.swift
> +    func businessLogic(into state: inout State, action: Action) -> EffectTask<Action> {
Referencing from the TCA examples, typically these function would return a `some ReducerProtocol` instead of `EffectTask`. I'd suggest wrapping the `Reduce(...)` here in the `businessLogic` function. Very nit though.

2023-04-07 18:34 UTC, superx3man commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/InternalNotificationTray.swift
> +            for i in (0..<state.notifications.count) {
`for index in state.notifications.indices`

2023-04-07 18:34 UTC, superx3man commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/InternalNotificationTray.swift
> +    let openNotification: (NotificationFeature.PostId) -> Void
If we have `NotificationTrayClient` can these be properties inside the client struct?

2023-04-07 18:34 UTC, superx3man commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/InternalNotificationTray.swift
> +    typealias ViewStore = ViewStoreOf<InternalNotificationTray>
nit: these typealias feels a bit redundant.

2023-04-07 18:34 UTC, superx3man commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/NotificationFeature.swift
> +        self.openNotification = openNotification
This!

2023-04-07 18:34 UTC, superx3man commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/InternalNotificationTray.swift
> +        self.openNotification = openNotification
I think `openNotification` most likely should be returning a closure returning `Effect<Void>` instead of being a void closure.

2023-04-07 18:34 UTC, superx3man commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/NotificationFeature.swift
> +            return markNotificationAsRead(state.id).fireAndForget()
`openNotification` should be a closure that returns `Effect<Void>`, that provides an effect of pushing a VC. And I think these 2 effects should be combined to one single effect.

2023-04-07 18:34 UTC, superx3man commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/NotificationFeature.swift
> +    }
Do we need a custom struct for a `String` value? Unless we are doing some fancy `init` pattern that does sth like
```
struct PostId {
  init?(url: URL) {
    // regular expression check, return nil if not applicable.
  }
}
```
but I felt like string probably is fine?

2023-04-07 18:34 UTC, superx3man commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/UIViewController+Tooltip.swift
> +                                self?.presentedViewController?.dismiss(animated: true)
Should we keep the `onDidClose` callback completion trigger?

2023-04-07 18:34 UTC, superx3man commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/UIViewController+Tooltip.swift
> +                                }
Do we have to chain these action with completion blocks or they could potentially work in parallel?
```
self?.presentedViewController?.dismiss(animated: true)
let viewController = AmityPostDetailViewController.make(withPostId: postId.value)
self?.navigationController?.pushViewController(viewController, animated: true)
```

2023-04-10 21:20 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/NotificationFeature.swift
> +    }
Yea, it was getting confusing as there are two methods with different String identifiers, especially considering they were inject via closures which don't have named parameters to distinguish them.

2023-04-17 19:26 UTC, superx3man requested changes
Overall looks good, but I think it's worth adding the fetching logic directly in this PR, it probably is like 5-10 lines of code.

2023-04-17 19:26 UTC, superx3man commented on Package.swift
> +        .package(url: "https://github.com/pointfreeco/swift-composable-architecture.git", exact: "0.52.0"),
nit: indentation

2023-04-17 19:26 UTC, superx3man commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/UIViewController+NavbarTooltip.swift
> +                                uniqueElements: self.getMockNotifications().map(NotificationRow.State.init)
if you are leaving the `mock` logic in, you should not merge this until you have it replace by the fetching logic.

2023-04-17 19:26 UTC, superx3man commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/UIViewController+NavbarTooltip.swift
> +                                uniqueElements: self.getMockNotifications().map(NotificationRow.State.init)
Tbh I think the logic here should be relatively simple, basically just triggering the `GetNotifications` effect on screen appear and setting the state value.

2023-04-17 20:43 UTC, aabolade commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/UIViewController+NavbarTooltip.swift
> +                                uniqueElements: self.getMockNotifications().map(NotificationRow.State.init)
Oh I need to remove this mock logic actually!

Also the fetch needs to happen before when the nav bar item is tapped inside `AmityHomePageViewController.swift` And I will do this In the next PR

2023-04-18 14:44 UTC, superx3man commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Home/AmityCommunityHomePageViewController.swift
> +        #warning("TODO: uncomment the line below and then delete the line above when notifications is ready to be relaesed")
Just add a comment is fine here! in a format of sth like
`TODO(Jira ticket code): Set right bar buttons to include notification bell`

I suggest removing the commented code as well, similar to how you removed the mock stuff, keeping the code clean.

2023-04-18 16:35 UTC, merged