Make anonymous communities unable to view member list
noom/Noom-Amity-Social-UIKit pull request #13
Opened 2023-04-14 19:18 UTC by cznrhubarb

B2B has a requirement for anonymous communities, which are just communities that have the member list inaccessible.

This PR turns off the member list button and hides the label that is normally the member list button (so as not to appear as a bug).

This has been tested manually.

2023-04-14 19:44 UTC, ilyap7o requested changes
Optional unwrap needs a quick fix, otherwise LG!

2023-04-14 19:44 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community List/Model/AmityCommunitiesModel.swift
> +    public static let commentsHiddenKey = "areCommentsHidden"
Whitespace change? 🤔

2023-04-14 19:44 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Profile/ViewController/Child/AmityCommunityProfileHeaderViewController.swift
> +            let memberCount = community!.membersCount
To unwrap a Swift optional in a scope you can use `if let`:
```
if let community = community {
    // `community` is now non-Optional in the if's scope
```

As if a few Swift releases ago, you can even avoid the assignment if you're keeping the name the same: `if let community { ...`

We like avoid force-unwraps (`!`) at all costs. So, please change this to:
```
if !isAnonymous, let community {  // Commas are the same as `&&` and are generally preferred
    let memberCount = community.membersCount  // Might not even need this variable anyway
```

2023-04-14 19:44 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Profile/ViewController/Parent/AmityCommunityProfilePageViewController.swift
> +            if !isAnonymous {
Just want to double-check that `isAnonymous`'s default should `false`, like in cases where `metadata` is nil or the key value is missing. Seems reasonable, but good to think about which side of it the `nil` case would fall under.

2023-04-17 21:28 UTC, cznrhubarb commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community List/Model/AmityCommunitiesModel.swift
> +    public static let commentsHiddenKey = "areCommentsHidden"
Yea, I guess there was a trailing space at the end of the line. (you can see it if you highlight it in the before and after 😉)

2023-04-17 21:28 UTC, cznrhubarb commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Profile/ViewController/Parent/AmityCommunityProfilePageViewController.swift
> +            if !isAnonymous {
Correct, we're not going to migrate the metadata on the communities to make this explicit and required, and the default is that they should stay as they are now unless we specifically say otherwise.

2023-04-17 21:35 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community List/Model/AmityCommunitiesModel.swift
> +    public static let commentsHiddenKey = "areCommentsHidden"
Ok, just checking cuz once I somehow added an invisible unicode symbol that the compiler parsed and complained about (the error was nowhere near the problem, of course) 😅

2023-04-17 21:37 UTC, ilyap7o approved these changes

2023-04-17 21:44 UTC, merged