adding badge and making call to fetch notifications
noom/Noom-Amity-Social-UIKit pull request #14
Opened 2023-04-18 19:39 UTC by aabolade

### JIRA link: https://noomhq.atlassian.net/browse/LTRGTR-166

## Description

Implementing fetching notifications in Community home page and adding badge count to notifications navigation item

## Screenshots

<img width="374" alt="Screenshot 2023-04-18 at 19 35 22" src="https://user-images.githubusercontent.com/15912313/232887227-6030c7a7-34fd-4325-830e-f68356dbad3d.png">

---

### Checklist

**Internationalization:** _(all strings must be localised. See [docs](https://github.com/noom/mobile-handbook/blob/master/general/tms.md))_
- [ ] All my strings were added to a `.strings` file so Smartling can initiate its workflow.

**Experimentation flags:** _List the ECT and/or Firebase flag names._
- [ ] I have created a RemoteConfig kill-switch if my experiment uses ECT.

**Unit tests:**
- [ ] My changes are covered with unit tests. If not, here's why: _Your explanation for why unit tests are unnecessary._

2023-04-18 21:00 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Home/AmityCommunityHomePageViewController.swift
> +        label.tag = 9830384
What's up with this tag number?

2023-04-18 21:03 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Home/AmityCommunityHomePageViewController.swift
> +    private let badgeSize: CGFloat = 20
I think I'd make this slightly smaller based on the screenshot. Looks a little big to me, but that's totally subjective.

2023-04-19 12:37 UTC, aabolade commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Home/AmityCommunityHomePageViewController.swift
> +                    print(notifications)
Just for testing

2023-04-19 12:37 UTC, aabolade commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Home/AmityCommunityHomePageViewController.swift
> +        ])
Good idea!

2023-04-19 15:05 UTC, aabolade commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Home/AmityCommunityHomePageViewController.swift
> +        badgeCountLabel.text = String(count)
It actually doesn't look too bad 😄 
<img width="83" alt="Screenshot 2023-04-19 at 15 04 31" src="https://user-images.githubusercontent.com/15912313/233118430-1fc571fe-d632-451e-9475-fe37a694c3ac.png">

2023-04-19 15:05 UTC, aabolade commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Home/AmityCommunityHomePageViewController.swift
> +        label.tag = 9830384
Ah I was going to use this to remove it from the view. Will delete

2023-04-19 15:58 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Home/AmityCommunityHomePageViewController.swift
> +        badgeCountLabel.text = String(count)
Great! Nevermind then!

2023-04-19 16:07 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Home/AmityCommunityHomePageViewController.swift
> +        _ = client
I don't recall if the `_ =` works for Combine `Cancellable`s, but I wanna say it doesn't? (unlike it does for RxSwift). Might have to assign to a VC instance var to retain the subscription until it completes.

2023-04-19 16:46 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Home/AmityCommunityHomePageViewController.swift
> +        _ = client
For an observable stream (`Publisher` in Combine, `Observable`/`Driver` in RxSwift) to actually execute, it needs to be subscribed to. The subscription produces a `Cancellable` (or `Disposable` in Rx) that you have to hold on to for the stream to be active, otherwise it gets cleaned up.

What I was saying is that I'm not sure this would work in Combine like it does in RxSwift, where you can do `_ = Observable.subscribe()` and have it run. On a closer look, I it doesn't look like you're subscribing at all (`.sink()` in Combine) so that's probably why this isn't working even if you do inject a `notificationAPIClient` in.

2023-04-20 10:22 UTC, aabolade commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Home/AmityCommunityHomePageViewController.swift
> +                    print(error)
Thinking of making this an `if case` since I'm not sure about how we want to do error handling if these calls fail 🤔

2023-04-20 18:02 UTC, ilyap7o requested changes
Looks better!

But, I did find a pretty big opportunity for improvement around the two API calls you're making. Currently, you're calling `getNotifications` and `getNotificationTrayUser` **serially** (one after the other), even though the second call doesn't require input from the first (their **results** are combined, but the `getNotificationTrayUser` doesn't need `getNotifications`'s output to be invoked). This is the perfect opportunity to make those calls **in parallel** and combine the results.

I think this would be a really good exercise for you to try to solve 🙂 Slack me if you need help or a hint!

2023-04-20 18:34 UTC, aabolade commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/Noom Tooltip/Extensions.swift
> -
So the issue here was that the server was returning different formats of the iso8601 date - with different fractional seconds so sometimes this formatter wasn't capturing the date correclty

2023-04-20 19:11 UTC, aabolade commented
> Looks better!
> 
> But, I did find a pretty big opportunity for improvement around the two API calls you're making. Currently, you're calling `getNotifications` and `getNotificationTrayUser` **serially** (one after the other), even though the second call doesn't require input from the first (their **results** are combined, but the `getNotificationTrayUser` doesn't need `getNotifications`'s output to be invoked). This is the perfect opportunity to make those calls **in parallel** and combine the results.
> 
> I think this would be a really good exercise for you to try to solve 🙂 Slack me if you need help or a hint!

changes applied!

2023-04-20 19:21 UTC, ilyap7o approved these changes
Nice!!

Small defensive change suggestion, otherwise LG!

2023-04-20 19:21 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/Noom Tooltip/Extensions.swift
> -
Oooh, I see now. Makes sense!

2023-04-20 19:21 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Home/AmityCommunityHomePageViewController.swift
> +        guard count > 0 else { return }
Good idea to do `badgeCountLabel.isHidden = true` in the zero case, just to be defensive. I know it starts out hidden, but if we were use this func to update the badge count without recreating the VC it'll show stale data.

2023-04-20 19:34 UTC, merged