Adeleke/ltrgtr 167/UI updates
noom/Noom-Amity-Social-UIKit pull request #2
Opened 2023-04-24 23:04 UTC by aabolade

### JIRA link: https://noomhq.atlassian.net/browse/LTRGTR-167

## Description

Implementing UI updates to match with suggested [Figma designs](https://www.figma.com/file/HP3BWmFoZykzyNld4Vqsuv/Notifications-for-IOS?node-id=2%3A1203&t=IIJeIdwyf1wEYEa1-1)

## Screenshots

<img width="339" alt="Screenshot 2023-04-21 at 23 16 27" src="https://user-images.githubusercontent.com/15912313/233748059-85ad8fbb-627c-4c6f-ac50-976dc82e47e3.png">
---

### Checklist

**Internationalization:** _(all strings must be localised. See [docs](https://github.com/noom/mobile-handbook/blob/master/general/tms.md))_
- [ ] All my strings were added to a `.strings` file so Smartling can initiate its workflow.

**Experimentation flags:** _List the ECT and/or Firebase flag names._
- [ ] I have created a RemoteConfig kill-switch if my experiment uses ECT.

**Unit tests:**
- [ ] My changes are covered with unit tests. If not, here's why: _Your explanation for why unit tests are unnecessary._

2023-04-24 23:23 UTC, ilyap7o requested changes

2023-04-24 23:23 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/Noom Tooltip/Extensions/Fonts.swift
> +    static let noomRegularBold = UIFont.systemFont(ofSize: 14, weight: .bold)
Should this be using `noomFontRegular(...)` above?

If not, this naming is confusing as this is system font, not Noom

2023-04-24 23:23 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/NotificationRow.swift
> +                        return URLSession.shared.dataTaskPublisher(for: url)
Fix intentation

2023-04-24 23:23 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/NotificationRow.swift
> +        case .imageFailed: return .none
I don't think we need `case imageFailed` if we're not doing anything. Moot if you combine both to `.imageResponse(let result)`

2023-04-24 23:23 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/NotificationRow.swift
> +                       .receive(on: RunLoop.main)
Add `@Dependency(\.mainQueue) var mainQueue` in the reducers `var`s, and do `.receive(on: mainQueue` here

2023-04-24 23:23 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/NotificationRow.swift
> +        case imageFetched(UIImage)
Combine these into
```
case imageResponse(Result<Data, Error>)
```

Then below, you can simply do:
```
return URLSession.shared.dataTaskPublisher(for: url)
    .recieve(on: mainQueue)
    .catchToEffect(Action.imageResponse)
```
(Global search our codebase for `.catchToEffect(Action.` for examples)

Then, handle the `switch result` in `case .imageResponse`, setting the state image if there's a valid one

2023-04-24 23:42 UTC, aabolade commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/Noom Tooltip/Extensions/Fonts.swift
> +    static let noomRegularBold = UIFont.systemFont(ofSize: 14, weight: .bold)
Fair enough, I think this extension may be redundant tbh

2023-04-25 00:08 UTC, ilyap7o approved these changes
LG! Nits only

2023-04-25 00:08 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/NotificationRow.swift
> +                            Circle().fill(Color(.backgroundGrey))
(Nit) `.fill(...)` on new line

2023-04-25 00:08 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/Noom Tooltip/Extensions/Colors.swift
> +    static let greyThree = UIColor(red: 0.4, green: 0.4, blue: 0.4, alpha: 1)
(Nit) Call it `grey3` to be consistent with `coach-ios`

2023-04-25 00:08 UTC, ilyap7o commented on UpstraUIKit/UpstraUIKit/Modules/Comunity/Community Notifications/NotificationRow.swift
> +                .mapError { $0 }
What does this do? I thought `catchToEffect` would type-erase everything as needed 🤷‍♂️

2023-04-25 15:40 UTC, merged